# .github/workflows/backtest_workflow.yml

name: Backtest Trading System (2015)

# --- QUANDO ESEGUIRE IL WORKFLOW ---
on:
  # 1. Esegui automaticamente quando fai un push sul branch 'main'
  push:
    branches: [ main ]
    
  # 2. Permette di avviare il workflow manualmente dalla pagina "Actions" di GitHub
  workflow_dispatch:

# --- I COMPITI DA SVOLGERE ---
jobs:
  build-and-backtest:
    # Usa l'ultima versione di Ubuntu come sistema operativo
    runs-on: ubuntu-latest

    # --- I PASSAGGI DEL PROCESSO ---
    steps:
      # Passaggio 1: Scarica il codice dal tuo repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # Passaggio 2: Prepara l'ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Una versione stabile e compatibile

      # Passaggio 3: Installa tutte le librerie necessarie
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Passaggio 4: Esegui lo script principale del backtest
      - name: Run the Backtest Orchestrator
        run: python backtest_orchestrator.py

      # Passaggio 5: Salva i risultati generati
      - name: Upload Backtest Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backtest-results-2015
          path: |
            backtest_results.csv
            data_backtest/ai_learning/performance.db
            data_backtest/reports/Report_Olga_Trade.html
            data_backtest/trading_integrated.log
